python3 test/test.py


Traceback (most recent call last):
  File "test/test.py", line 16, in <module>
    shallow(bar, [31m15[m)
    [36mâ”‚       â”” 2[m
    [36mâ”” <function shallow at 0xDEADBEEF>[m
  File "test/test.py", line 7, in shallow
    deep(a + b)
    [36mâ”‚    â”‚   â”” 15[m
    [36mâ”‚    â”” 2[m
    [36mâ”” <function deep at 0xDEADBEEF>[m
  File "test/test.py", line 12, in deep
    [33;1massert[m val > [31m10[m and foo == [31m60[m
    [36m       â”‚            â”” 52[m
    [36m       â”” 17[m
AssertionError: [33;1massert[m val > [31m10[m and foo == [31m60[m



python3 test/test_color.py


True



./test/test_interactive.sh


spawn python3 -m better_exceptions -q
>>> import better_exceptions
>>> def foo(a):
...     assert a > 10
... 
>>> foo(1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
    foo([31m1[m)
    [36mâ”” <function foo at 0xDEADBEEF>[m
  File "<console>", line 2, in foo
    [33;1massert[m a > [31m10[m
    [36m       â”” 1[m
AssertionError: [33;1massert[m a > [31m10[m
>>> exit()



./test/test_interactive_raw.sh


spawn python3 -m test_util.quiet_console
>>> import better_exceptions
WARNING: better_exceptions will not inspect code from the command line
         using: `python -m better_exceptions'. Otherwise, only code
         loaded from files will be inspected!
>>> def foo(a):
...     assert a > 10
... 
>>> foo(1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<console>", line 2, in foo
AssertionError
>>> exit()



./test/test_string.sh



import better_exceptions; a = 5; assert a > 10 # this should work fine

Traceback (most recent call last):
  File "<string>", line 1, in <module>
    [33;1mimport[m better_exceptions; a = [31m5[m; [33;1massert[m a > [31m10[m [2;37m# this should work fine[m
    [36m                          â”‚             â”” 5[m
    [36m                          â”” 5[m
AssertionError: [33;1mimport[m better_exceptions; a = [31m5[m; [33;1massert[m a > [31m10[m [2;37m# this should work fine[m

Traceback (most recent call last):
  File "<string>", line 1, in <module>
    [33;1mimport[m better_exceptions; a = [31m5[m; [33;1massert[m a > [31m10[m [2;37m# this should work fine[m
    [36m                          â”‚             â”” 5[m
    [36m                          â”” 5[m
AssertionError: [33;1mimport[m better_exceptions; a = [31m5[m; [33;1massert[m a > [31m10[m [2;37m# this should work fine[m

from __future__ import print_function; import better_exceptions; a = "why hello there"; print(a); assert False

why hello there
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from __future__ import print_function; [33;1mimport[m better_exceptions; a = [31m'why hello there'[m; [35;1mprint[m(a); [33;1massert[m False
    [36m                                                                 â”‚                            â”” 'why hello there'[m
    [36m                                                                 â”” 'why hello there'[m
AssertionError: from __future__ import print_function; [33;1mimport[m better_exceptions; a = [31m'why hello there'[m; [35;1mprint[m(a); [33;1massert[m False

why hello there
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from __future__ import print_function; [33;1mimport[m better_exceptions; a = [31m'why hello there'[m; [35;1mprint[m(a); [33;1massert[m False
    [36m                                                                 â”‚                            â”” 'why hello there'[m
    [36m                                                                 â”” 'why hello there'[m
AssertionError: from __future__ import print_function; [33;1mimport[m better_exceptions; a = [31m'why hello there'[m; [35;1mprint[m(a); [33;1massert[m False

from __future__ import print_function; import better_exceptions; a = "why     hello          " + "   there"; print(a); assert False

why     hello             there
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from __future__ import print_function; [33;1mimport[m better_exceptions; a = [31m'why     hello          '[m + [31m'   there'[m; [35;1mprint[m(a); [33;1massert[m False
    [36m                                                                 â”‚                                                 â”” 'why     hello             there'[m
    [36m                                                                 â”” 'why     hello             there'[m
AssertionError: from __future__ import print_function; [33;1mimport[m better_exceptions; a = [31m'why     hello          '[m + [31m'   there'[m; [35;1mprint[m(a); [33;1massert[m False

why     hello             there
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from __future__ import print_function; [33;1mimport[m better_exceptions; a = [31m'why     hello          '[m + [31m'   there'[m; [35;1mprint[m(a); [33;1massert[m False
    [36m                                                                 â”‚                                                 â”” 'why     hello             there'[m
    [36m                                                                 â”” 'why     hello             there'[m
AssertionError: from __future__ import print_function; [33;1mimport[m better_exceptions; a = [31m'why     hello          '[m + [31m'   there'[m; [35;1mprint[m(a); [33;1massert[m False



